/**
 * UI strings (EN). Every user-facing string in @rmmm/ui lives here so it can be translated.
 * Copy rules (SPEC 14): plain, kind, neutral about named parties. No em dashes, no emojis,
 * never "scammer" or "fraud" as a statement of fact.
 */
export const en = {
  stamp: {
    reported: 'Reported',
    verifying: 'Verifying',
    contacted: 'Contacted',
    response_received: 'Response received',
    no_response: 'No response',
    resolved_refunded: 'Resolved: refunded',
    resolved_other: 'Resolved',
    closed: 'Closed',
    alleged: 'Alleged',
    verified: 'Verified',
    no_refunds: 'No refunds',
  },
  evidence: {
    reported: (n: number) => `Reported ${n} ${n === 1 ? 'time' : 'times'}`,
    reviewed: (n: number) => `${n} reviewed`,
    lost: (amount: string) => `${amount} reported lost`,
    lastReport: (ago: string) => `Last report ${ago}`,
    linkedPages: (n: number) => `Linked pages: ${n}`,
    underReviewTitle: 'Reports under review',
    underReviewBody:
      'Something matched, but it has not been reviewed yet. Nothing is shown until a person checks the receipts.',
    noResultsTitle: 'No reports yet.',
    noResultsBody: "That's not a guarantee.",
  },
  whyMatched: {
    title: 'Why this matched',
    shared_cashtag: 'Same Cash App tag',
    shared_phone: 'Same phone',
    shared_payment: 'Same payment account',
    same_flyer_phash: 'Same flyer image',
    name_similarity: 'Name similar to',
    loose_handle: 'Similar handle',
    exact_handle: 'Same handle',
    staff_manual: 'Linked by our team',
  },
  linkedPages: {
    title: 'Linked pages',
    empty: 'No linked pages.',
  },
  envelope: {
    emptyTitle: 'No case yet',
    emptyBody: 'Cases show up here once our team opens one.',
    caseNumber: 'Case number',
  },
  receipt: {
    paid: 'Paid',
    rail: 'Paid with',
    date: 'Date',
  },
  common: {
    loading: 'Loading',
    alleged: 'Alleged',
    continue: 'Continue',
    back: 'Back',
    tryAgain: 'Something went wrong. Try again.',
  },
  security: {
    blocked:
      'Access from this network or device has been blocked. If you think this is a mistake, contact us.',
    slowDown: 'Too many requests. Wait a moment and try again.',
  },
  auth: {
    title: 'Sign in',
    nav: 'Sign in',
    lede: 'We will send you a one-time code. No password needed.',
    contactLabel: 'Email or phone number',
    contactHint: 'US numbers can skip the +1.',
    sendCode: 'Send code',
    sending: 'Sending',
    codeSentTo: (to: string) => `We sent a code to ${to}.`,
    codeLabel: '6-digit code',
    verify: 'Verify',
    verifying: 'Checking',
    useDifferent: 'Use a different email or phone',
    invalidContact: 'Enter a valid email address or phone number.',
    invalidCode: 'That code did not work. Check it and try again.',
    notConfigured: 'Sign in is not set up in this environment yet.',
    signOut: 'Sign out',
    turnstileLabel: 'Verification',
  },
  onboarding: {
    title: 'Before you start',
    lede: 'Stories here can be heavy. You need to be 18 or older to make an account or send a report.',
    birthDateLabel: 'Date of birth',
    month: 'MM',
    day: 'DD',
    year: 'YYYY',
    birthDateHint: 'We only use this to check your age. We do not save it.',
    termsLabel: 'I agree to the Terms of Service and Privacy Policy.',
    termsLinks: 'Read the Terms and the Privacy Policy',
    submit: 'Continue',
    under18Title: 'You need to be 18 or older',
    under18Body:
      'You can still look up businesses and watch episodes without an account. If you lost money, a trusted adult can help you report it.',
    invalidDate: 'Enter your date of birth.',
    termsRequired: 'You need to agree to the Terms and Privacy Policy to continue.',
  },
  site: {
    name: 'RUN ME MY MONEY',
    tagline: 'Look them up before you pay.',
    description:
      'Search a business, @handle, Cash App tag or phone before you pay a deposit. Share your story with receipts. Follow the cases from the series.',
    skipToContent: 'Skip to content',
    home: 'RUN ME MY MONEY home',
  },
  nav: {
    label: 'Main',
    lookup: 'Lookup',
    resources: 'Resources',
    about: 'About',
    contact: 'Contact',
    menu: 'Menu',
    closeMenu: 'Close menu',
    openMenu: 'Open menu',
    current: 'current page',
    commandHint: 'Search pages',
    footer: 'Footer',
    legal: 'Legal',
    privacySettings: 'Privacy settings',
    shortcuts: 'Keyboard shortcuts',
    home: 'Home',
  },
  pages: {
    draft: (v: string) => `DRAFT, version ${v}. Pending review by counsel.`,
    reviewed: (d: string) =>
      `Last reviewed ${d}. Rules change: check the official page for the current process.`,
    notLegalAdvice: 'General information, not legal advice.',
    officialLink: 'Official page',
    exampleData: 'Example with made-up data',
  },
  footer: {
    operatedBy: (product: string, company: string) => `${product}. Operated by ${company}.`,
    notLegalAdvice: 'Resources on this site are general information, not legal advice.',
    shortcutBefore: 'Press',
    shortcutOr: 'or',
    shortcutAfter: 'to jump to any page.',
    copyright: (year: number, company: string) => `Copyright ${year} ${company}`,
  },
  theme: {
    label: 'Theme',
    system: 'System',
    dark: 'Dark',
    light: 'Light',
    change: (current: string) => `Theme: ${current}. Change theme`,
  },
  palette: {
    title: 'Go to',
    placeholder: 'Type a page or action',
    empty: 'Nothing matches that. Try "lookup", "contact" or "privacy".',
    results: (n: number) => `${n} ${n === 1 ? 'result' : 'results'}`,
    hint: 'Ctrl K',
    keys: { move: 'move', open: 'open', close: 'close', anywhere: 'anywhere' },
    groupPages: 'Pages',
    groupActions: 'Actions',
  },
  network: {
    offline:
      'You appear to be offline. Pages you already opened still work. Anything you send will wait until you are back.',
    backOnline: 'Back online.',
  },
  errors: {
    notFoundTitle: 'Nothing filed under this address',
    notFoundBody:
      'The page may have moved, or the link has a typo. Here is the address, broken into the parts you can still use.',
    notFoundPath: 'Path',
    goHome: 'Go to the home page',
    serverTitle: 'Something broke on our side',
    serverBody:
      'It is not you. Try again in a moment. If it keeps happening, tell us what you were doing.',
    retry: 'Try again',
    contactUs: 'Contact us',
    reference: (id: string) => `Reference: ${id}`,
  },
  cookies: {
    bannerTitle: 'Your privacy choices',
    bannerBody:
      'We use necessary cookies to keep you signed in and to stop abuse. With your OK we also count visits anonymously so we know what helps. No ads, no selling data.',
    acceptAll: 'Allow analytics',
    rejectAll: 'Necessary only',
    customize: 'Choose',
    saved: 'Your privacy choices are saved.',
    saveFailed: 'Your choices were not saved. Try again.',
    save: 'Save my choices',
    necessary: 'Necessary',
    necessaryBody:
      'Sign-in session, abuse prevention (a random device id) and remembering these choices. Always on.',
    alwaysOn: 'Always on',
    preferences: 'Preferences',
    preferencesBody:
      'Remembers light or dark mode when you pick one. Set only when you choose a theme.',
    analytics: 'Analytics',
    analyticsBody:
      'Anonymous visit counts (Plausible). No cookies, no personal data, IP addresses are not stored.',
    analyticsUnavailable:
      'Not in use on this site right now. Your choice will be respected if it is turned on.',
    marketing: 'Marketing',
    marketingBody: 'We do not use marketing or advertising cookies. There is nothing to turn on.',
    on: 'On',
    off: 'Off',
    version: (v: string) => `Policy version ${v}`,
  },
  forms: {
    required: 'Required',
    allRequired: 'All fields are required.',
    chooseOne: 'Choose one',
    optional: 'optional',
    fixErrors: (n: number) => `Fix ${n} ${n === 1 ? 'problem' : 'problems'} before sending.`,
    sending: 'Sending',
    sent: 'Sent',
    networkError:
      'We could not reach the server. Your text is still here. Check your connection and try again.',
    serverError: 'That did not go through on our side. Your text is still here. Try again.',
    rateLimited: 'Too many tries in a short time. Wait a minute, then try again.',
  },
  contact: {
    title: 'Contact',
    lede: 'Questions about a case, a business response, press, or a safety concern. We read everything. To report a business, use the report flow when it opens, not this form.',
    reason: 'What is this about?',
    reasons: {
      business: 'I run a business mentioned here',
      press: 'Press or partnership',
      legal: 'Legal notice or takedown',
      safety: 'Safety concern',
      bug: 'Something on the site is broken',
      other: 'Something else',
    },
    name: 'Your name',
    email: 'Email for our reply',
    emailHint: 'Only used to answer you.',
    message: 'Message',
    messageHint: 'Do not include card numbers or passwords.',
    submit: 'Send message',
    successTitle: 'Message received',
    successBody: (ref: string) =>
      `Reference ${ref}. We reply to most messages within 3 business days.`,
    sendAnother: 'Send another message',
    errName: 'Tell us what to call you.',
    errEmail: 'Enter an email address we can reply to.',
    errReason: 'Pick what this is about.',
    errMessage: 'Write a message of at least 20 characters.',
    safetyNote: 'If you are in danger right now, call 911.',
  },
  deletion: {
    title: 'Delete my data',
    lede: 'Ask us to delete your account and the personal data tied to it.',
    whatHappens: 'What happens',
    steps: [
      'We confirm the request came from you (it is tied to your signed-in account).',
      'Within 30 days we delete your account, profile, watchlist, follows and notifications.',
      'Reports you sent are deleted or fully anonymized. Records we must keep by law (for example a legal hold on a case) are kept only as long as required.',
      'We email or text you when it is done.',
    ],
    confirm: 'I understand this cannot be undone.',
    submit: 'Request deletion',
    errConfirm: 'Tick the box to confirm.',
    doneTitle: 'Deletion requested',
    doneBody: 'We have your request. We will finish within 30 days and let you know.',
    pending: 'You already have a deletion request in progress.',
  },
  states: {
    suspendedTitle: 'This account is suspended',
    suspendedBody:
      'You can still look things up and read public pages. If you think this is a mistake, contact us.',
    sessionExpired: 'Your session ended. Sign in again to continue.',
  },
  account: {
    nav: 'Account',
    title: 'Your account',
    signedInAs: (who: string) => `Signed in as ${who}`,
    role: (r: string) => `Role: ${r}`,
    memberSince: (d: string) => `Member since ${d}`,
    signIn: 'Sign in',
    deleteLink: 'Delete my data',
    privacyLink: 'Privacy settings',
  },
  lookup: {
    title: 'Lookup',
    lede: 'Type anything they gave you: a business name, @handle, $cashtag, Zelle email or phone, phone number or website.',
    label: 'Business, @handle, $cashtag, phone, email or website',
    detected: 'Reads as',
    normalized: 'We search for',
    kinds: {
      cashtag: 'Cash App tag',
      handle: 'Social handle',
      phone: 'Phone number',
      email: 'Email address',
      domain: 'Website',
      name: 'Business name',
    },
    platforms: { ig: 'Instagram', tiktok: 'TikTok', fb: 'Facebook', x: 'X' },
    whyKind: {
      cashtag:
        'Payment tags are the strongest match. Pages change names; they rarely change where the money goes.',
      handle: 'We also check close variations, because rebrands often add a number or a dot.',
      phone: 'Every format of the same number is matched as one.',
      email: 'Zelle and PayPal often run on an email. Gmail dots and +tags are ignored.',
      domain: 'We match the site itself, not the page you were sent to.',
      name: 'Names are the weakest signal. Add a handle or payment tag if you have one.',
    },
    notYetTitle: 'Results open soon',
    notYetBody:
      'Search goes live once the first reports have been reviewed by our team. Until then, nothing about any business is shown, on purpose. Use the checklist below before you pay.',
    loadingProbe: 'Getting the checker ready',
  },
  time: {
    today: 'today',
    yesterday: 'yesterday',
    daysAgo: (n: number) => `${n} days ago`,
    weeksAgo: (n: number) => `${n} ${n === 1 ? 'week' : 'weeks'} ago`,
    monthsAgo: (n: number) => `${n} ${n === 1 ? 'month' : 'months'} ago`,
    yearsAgo: (n: number) => `${n} ${n === 1 ? 'year' : 'years'} ago`,
  },
} as const;

export type Strings = typeof en;
