/**
 * UI strings (EN). Every user-facing string in @rmmm/ui lives here so it can be translated.
 * Copy rules (SPEC 14): plain, kind, neutral about named parties. No em dashes, no emojis,
 * never "scammer" or "fraud" as a statement of fact.
 */
export const en = {
  stamp: {
    reported: 'Reported',
    verifying: 'Verifying',
    contacted: 'Contacted',
    response_received: 'Response received',
    no_response: 'No response',
    resolved_refunded: 'Resolved: refunded',
    resolved_other: 'Resolved',
    closed: 'Closed',
    alleged: 'Alleged',
    verified: 'Verified',
    no_refunds: 'No refunds',
  },
  evidence: {
    reported: (n: number) => `Reported ${n} ${n === 1 ? 'time' : 'times'}`,
    reviewed: (n: number) => `${n} reviewed`,
    lost: (amount: string) => `${amount} reported lost`,
    lastReport: (ago: string) => `Last report ${ago}`,
    linkedPages: (n: number) => `Linked pages: ${n}`,
    underReviewTitle: 'Reports under review',
    underReviewBody:
      'Something matched, but it has not been reviewed yet. Nothing is shown until a person checks the receipts.',
    noResultsTitle: 'No reports yet.',
    noResultsBody: "That's not a guarantee.",
  },
  whyMatched: {
    title: 'Why this matched',
    shared_cashtag: 'Same Cash App tag',
    shared_phone: 'Same phone',
    shared_payment: 'Same payment account',
    same_flyer_phash: 'Same flyer image',
    name_similarity: 'Name similar to',
    loose_handle: 'Similar handle',
    exact_handle: 'Same handle',
    staff_manual: 'Linked by our team',
  },
  linkedPages: {
    title: 'Linked pages',
    empty: 'No linked pages.',
  },
  envelope: {
    emptyTitle: 'No case yet',
    emptyBody: 'Cases show up here once our team opens one.',
    caseNumber: 'Case number',
  },
  receipt: {
    paid: 'Paid',
    rail: 'Paid with',
    date: 'Date',
  },
  common: {
    loading: 'Loading',
    alleged: 'Alleged',
    continue: 'Continue',
    back: 'Back',
    tryAgain: 'Something went wrong. Try again.',
  },
  security: {
    blocked:
      'Access from this network or device has been blocked. If you think this is a mistake, contact us.',
    slowDown: 'Too many requests. Wait a moment and try again.',
  },
  auth: {
    title: 'Sign in',
    nav: 'Sign in',
    lede: 'We will send you a one-time code. No password needed.',
    contactLabel: 'Email or phone number',
    contactHint: 'US numbers can skip the +1.',
    sendCode: 'Send code',
    sending: 'Sending',
    codeSentTo: (to: string) => `We sent a code to ${to}.`,
    codeLabel: '6-digit code',
    verify: 'Verify',
    verifying: 'Checking',
    useDifferent: 'Use a different email or phone',
    invalidContact: 'Enter a valid email address or phone number.',
    invalidCode: 'That code did not work. Check it and try again.',
    notConfigured: 'Sign in is not set up in this environment yet.',
    signOut: 'Sign out',
    turnstileLabel: 'Verification',
  },
  onboarding: {
    title: 'Before you start',
    lede: 'Stories here can be heavy. You need to be 18 or older to make an account or send a report.',
    birthDateLabel: 'Date of birth',
    month: 'MM',
    day: 'DD',
    year: 'YYYY',
    birthDateHint: 'We only use this to check your age. We do not save it.',
    termsLabel: 'I agree to the Terms of Service and Privacy Policy.',
    termsLinks: 'Read the Terms and the Privacy Policy',
    submit: 'Continue',
    under18Title: 'You need to be 18 or older',
    under18Body:
      'You can still look up businesses and watch episodes without an account. If you lost money, a trusted adult can help you report it.',
    invalidDate: 'Enter your date of birth.',
    termsRequired: 'You need to agree to the Terms and Privacy Policy to continue.',
  },
  site: {
    name: 'RUN ME MY MONEY',
    tagline: 'Look them up before you pay.',
    description:
      'Search a business, @handle, Cash App tag or phone before you pay a deposit. Share your story with receipts. Follow the cases from the series.',
    skipToContent: 'Skip to content',
    home: 'RUN ME MY MONEY home',
  },
  nav: {
    label: 'Main',
    lookup: 'Lookup',
    resources: 'Resources',
    about: 'About',
    contact: 'Contact',
    menu: 'Menu',
    closeMenu: 'Close menu',
    openMenu: 'Open menu',
    current: 'current page',
    commandHint: 'Search pages',
    footer: 'Footer',
    legal: 'Legal',
    privacySettings: 'Privacy settings',
    shortcuts: 'Keyboard shortcuts',
    home: 'Home',
  },
  pages: {
    draft: (v: string) => `DRAFT, version ${v}. Pending review by counsel.`,
    reviewed: (d: string) =>
      `Last reviewed ${d}. Rules change: check the official page for the current process.`,
    notLegalAdvice: 'General information, not legal advice.',
    officialLink: 'Official page',
    exampleData: 'Example with made-up data',
  },
  footer: {
    operatedBy: (product: string, company: string) => `${product}. Operated by ${company}.`,
    notLegalAdvice: 'Resources on this site are general information, not legal advice.',
    shortcutBefore: 'Press',
    shortcutOr: 'or',
    shortcutAfter: 'to jump to any page.',
    copyright: (year: number, company: string) => `Copyright ${year} ${company}`,
  },
  theme: {
    label: 'Theme',
    system: 'System',
    dark: 'Dark',
    light: 'Light',
    change: (current: string) => `Theme: ${current}. Change theme`,
  },
  palette: {
    title: 'Go to',
    placeholder: 'Type a page or action',
    empty: 'Nothing matches that. Try "lookup", "contact" or "privacy".',
    results: (n: number) => `${n} ${n === 1 ? 'result' : 'results'}`,
    hint: 'Ctrl K',
    keys: { move: 'move', open: 'open', close: 'close', anywhere: 'anywhere' },
    groupPages: 'Pages',
    groupActions: 'Actions',
  },
  network: {
    offline:
      'You appear to be offline. Pages you already opened still work. Anything you send will wait until you are back.',
    backOnline: 'Back online.',
  },
  errors: {
    notFoundTitle: 'Nothing filed under this address',
    notFoundBody:
      'The page may have moved, or the link has a typo. Here is the address, broken into the parts you can still use.',
    notFoundPath: 'Path',
    goHome: 'Go to the home page',
    serverTitle: 'Something broke on our side',
    serverBody:
      'It is not you. Try again in a moment. If it keeps happening, tell us what you were doing.',
    retry: 'Try again',
    contactUs: 'Contact us',
    reference: (id: string) => `Reference: ${id}`,
  },
  cookies: {
    bannerTitle: 'Your privacy choices',
    bannerBody:
      'We use necessary cookies to keep you signed in and to stop abuse. With your OK we also count visits anonymously so we know what helps. No ads, no selling data.',
    acceptAll: 'Allow analytics',
    rejectAll: 'Necessary only',
    customize: 'Choose',
    saved: 'Your privacy choices are saved.',
    saveFailed: 'Your choices were not saved. Try again.',
    save: 'Save my choices',
    necessary: 'Necessary',
    necessaryBody:
      'Sign-in session, abuse prevention (a random device id) and remembering these choices. Always on.',
    alwaysOn: 'Always on',
    preferences: 'Preferences',
    preferencesBody:
      'Remembers light or dark mode when you pick one. Set only when you choose a theme.',
    analytics: 'Analytics',
    analyticsBody:
      'Anonymous visit counts (Plausible). No cookies, no personal data, IP addresses are not stored.',
    analyticsUnavailable:
      'Not in use on this site right now. Your choice will be respected if it is turned on.',
    marketing: 'Marketing',
    marketingBody: 'We do not use marketing or advertising cookies. There is nothing to turn on.',
    on: 'On',
    off: 'Off',
    version: (v: string) => `Policy version ${v}`,
  },
  forms: {
    required: 'Required',
    allRequired: 'All fields are required.',
    chooseOne: 'Choose one',
    optional: 'optional',
    fixErrors: (n: number) => `Fix ${n} ${n === 1 ? 'problem' : 'problems'} before sending.`,
    sending: 'Sending',
    sent: 'Sent',
    networkError:
      'We could not reach the server. Your text is still here. Check your connection and try again.',
    serverError: 'That did not go through on our side. Your text is still here. Try again.',
    rateLimited: 'Too many tries in a short time. Wait a minute, then try again.',
  },
  contact: {
    title: 'Contact',
    lede: 'Questions about a case, a business response, press, or a safety concern. We read everything. To report a business, use Tell your story, not this form.',
    reason: 'What is this about?',
    reasons: {
      business: 'I run a business mentioned here',
      press: 'Press or partnership',
      legal: 'Legal notice or takedown',
      safety: 'Safety concern',
      bug: 'Something on the site is broken',
      other: 'Something else',
    },
    name: 'Your name',
    email: 'Email for our reply',
    emailHint: 'Only used to answer you.',
    message: 'Message',
    messageHint: 'Do not include card numbers or passwords.',
    submit: 'Send message',
    successTitle: 'Message received',
    successBody: (ref: string) =>
      `Reference ${ref}. We reply to most messages within 3 business days.`,
    sendAnother: 'Send another message',
    errName: 'Tell us what to call you.',
    errEmail: 'Enter an email address we can reply to.',
    errReason: 'Pick what this is about.',
    errMessage: 'Write a message of at least 20 characters.',
    safetyNote: 'If you are in danger right now, call 911.',
  },
  deletion: {
    title: 'Delete my data',
    lede: 'Ask us to delete your account and the personal data tied to it.',
    whatHappens: 'What happens',
    steps: [
      'We confirm the request came from you (it is tied to your signed-in account).',
      'Within 30 days we delete your account, profile, watchlist, follows and notifications.',
      'Reports you sent are deleted or fully anonymized. Records we must keep by law (for example a legal hold on a case) are kept only as long as required.',
      'We email or text you when it is done.',
    ],
    confirm: 'I understand this cannot be undone.',
    submit: 'Request deletion',
    errConfirm: 'Tick the box to confirm.',
    doneTitle: 'Deletion requested',
    doneBody: 'We have your request. We will finish within 30 days and let you know.',
    pending: 'You already have a deletion request in progress.',
  },
  states: {
    suspendedTitle: 'This account is suspended',
    suspendedBody:
      'You can still look things up and read public pages. If you think this is a mistake, contact us.',
    sessionExpired: 'Your session ended. Sign in again to continue.',
  },
  account: {
    nav: 'Account',
    title: 'Your account',
    signedInAs: (who: string) => `Signed in as ${who}`,
    role: (r: string) => `Role: ${r}`,
    memberSince: (d: string) => `Member since ${d}`,
    signIn: 'Sign in',
    deleteLink: 'Delete my data',
    privacyLink: 'Privacy settings',
  },
  lookup: {
    title: 'Lookup',
    lede: 'Type anything they gave you: a business name, @handle, $cashtag, Zelle email or phone, phone number or website.',
    label: 'Business, @handle, $cashtag, phone, email or website',
    detected: 'Reads as',
    normalized: 'We search for',
    kinds: {
      cashtag: 'Cash App tag',
      handle: 'Social handle',
      phone: 'Phone number',
      email: 'Email address',
      domain: 'Website',
      name: 'Business name',
    },
    platforms: { ig: 'Instagram', tiktok: 'TikTok', fb: 'Facebook', x: 'X' },
    whyKind: {
      cashtag:
        'Payment tags are the strongest match. Pages change names; they rarely change where the money goes.',
      handle: 'We also check close variations, because rebrands often add a number or a dot.',
      phone: 'Every format of the same number is matched as one.',
      email: 'Zelle and PayPal often run on an email. Gmail dots and +tags are ignored.',
      domain: 'We match the site itself, not the page you were sent to.',
      name: 'Names are the weakest signal. Add a handle or payment tag if you have one.',
    },
    notYetTitle: 'Results open soon',
    notYetBody:
      'Search goes live once the first reports have been reviewed by our team. Until then, nothing about any business is shown, on purpose. Use the checklist below before you pay.',
    loadingProbe: 'Getting the checker ready',
  },
  report: {
    nav: 'Tell your story',
    title: 'Tell your story',
    description:
      'Paid a business that ran off with your money? Tell us what happened, with receipts. Six short steps, saved as you go.',
    lede: 'Six short steps. Everything saves as you go, so you can stop and come back on this device.',
    privacyNote:
      'Your name, number, email and payment details are never shown publicly. A person on our team reads every report before anything about a business goes public.',
    quickExit: 'Quick exit',
    quickExitHint: 'Leaves this site right away. Your draft stays saved.',
    stepOf: (n: number, total: number) => `Step ${n} of ${total}`,
    steps: ['What happened', 'Who', 'Money', 'Receipts', 'Your story', 'You and consent', 'Review'],
    back: 'Back',
    next: 'Save and continue',
    start: 'Start',
    edit: 'Edit',
    saving: 'Saving',
    saved: 'Saved',
    notSaved: 'Not saved yet. Check your connection.',
    retrySave: 'Try again',
    loadingDraft: 'Opening your draft',
    unavailable:
      'Reports cannot be saved on this site right now. You can look through the steps, but nothing will be sent. Try again later.',
    resumed: 'We opened the draft you started earlier on this device.',
    startOver: 'Start a new report instead',
    category: {
      legend: 'What happened?',
      hint: 'Pick the one that fits best. Moderators can change it later.',
      error: 'Pick what happened.',
      options: {
        deposit_no_show: 'Took my deposit, then no-show',
        not_delivered: 'Paid, never got it',
        bad_service_no_refund: 'Bad service, no refund',
        credit_repair: 'Credit repair',
        forex_trading: 'Forex, trading or "investment"',
        fake_giveaway_clout: 'Fake giveaway or fake clout',
        romance_catfish: 'Romance or catfish',
        other: 'Something else',
      },
    },
    who: {
      legend: 'Who did you pay?',
      hint: 'Add everything you have. Payment tags and handles help us match reports about the same business, even after a name change. Give at least one.',
      error:
        'Add at least one way to identify them: a name, handle, phone, website or payment tag.',
      groupSocial: 'Social pages',
      groupPayment: 'Where the money went',
      groupPlace: 'Where they are',
      businessName: 'Business or person name',
      instagram: 'Instagram',
      tiktok: 'TikTok',
      facebook: 'Facebook page or link',
      x: 'X',
      phone: 'Phone number',
      website: 'Website',
      cashtag: 'Cash App $cashtag',
      zelle: 'Zelle email or phone',
      venmo: 'Venmo username',
      paypal: 'PayPal email or username',
      appleCash: 'Apple Cash phone or email',
      city: 'City',
      state: 'State',
      handleHint: 'Starts with @',
    },
    money: {
      legend: 'The money',
      hint: 'Rough numbers are fine. Leave out anything you do not know.',
      amount: 'How much did you pay?',
      amountError: 'Enter an amount like 250 or 250.00.',
      currency: 'Currency',
      paidOn: 'Date you paid',
      paidOnError: 'Enter a date that is not in the future.',
      rail: 'How did you pay?',
      rails: {
        cashapp: 'Cash App',
        zelle: 'Zelle',
        venmo: 'Venmo',
        paypal: 'PayPal',
        apple_cash: 'Apple Cash',
        card: 'Debit or credit card',
        bank: 'Bank transfer',
        crypto: 'Crypto',
        cash: 'Cash',
        other: 'Other',
      },
      wasDeposit: 'Was it a deposit?',
      refundRequested: 'Did you ask for a refund?',
      refundResponse: 'What did they say?',
      yes: 'Yes',
      no: 'No',
    },
    receipts: {
      legend: 'Receipts',
      hint: 'Screenshots of the chat, the payment, the flyer or the post. PDFs, voice notes (m4a, mp3) and short videos (60 seconds or less) work too. Up to 20 files.',
      metadataNote:
        'We remove location and camera details from every file. On this device, photos are cleaned before they leave your phone or computer; our server cleans everything again.',
      choose: 'Add files',
      choosePhotos: 'Add photos or screenshots',
      chooseFiles: 'Add PDF, audio or video',
      noWebUrl: 'This build of the app is not connected to our servers yet.',
      dropHint: 'or drop them here',
      redact: 'Hide details',
      remove: 'Remove',
      removeLabel: (name: string) => `Remove ${name}`,
      uploading: (pct: number) => `Uploading, ${pct}%`,
      queued: 'Waiting to upload',
      uploaded: 'Uploaded. Cleaning the file.',
      ready: 'Uploaded and cleaned',
      rejected: 'Not accepted',
      failed: 'Upload failed',
      retry: 'Try again',
      rejectReasons: {
        too_large: 'The file is too large.',
        type_mismatch: 'The file is not the type it claims to be.',
        infected: 'The file did not pass the virus check.',
        too_long: 'Recordings can be 60 seconds at most.',
        unreadable: 'We could not open the file.',
        processing_error: 'We could not process the file.',
      } as Record<string, string>,
      typeError: (name: string) => `${name}: that file type is not accepted.`,
      sizeError: (name: string, mb: number) =>
        `${name}: files of this type can be ${mb} MB at most.`,
      countError: 'A report can hold 20 files.',
      none: 'No files yet. Receipts are optional, but they help a lot.',
      fileCount: (n: number) => `${n} ${n === 1 ? 'file' : 'files'}`,
      waitForUploads: 'Wait for uploads to finish before you continue.',
    },
    redaction: {
      title: 'Hide details',
      hint: 'Draw boxes over names, numbers, faces or anything you want covered. Boxes become solid black in the file we receive.',
      keyboardHint:
        'Keyboard: Add box puts a box in the middle. Arrow keys move the selected box, Shift plus arrows resize it, Delete removes it.',
      addBox: 'Add box',
      blurFaces: 'Cover faces',
      facesFound: (n: number) =>
        n ? `Covered ${n} ${n === 1 ? 'face' : 'faces'}.` : 'No faces found. Draw boxes yourself.',
      undo: 'Remove last box',
      clear: 'Remove all boxes',
      apply: 'Use this version',
      cancel: 'Cancel',
      boxLabel: (n: number) => `Box ${n}`,
      boxCount: (n: number) => `${n} ${n === 1 ? 'box' : 'boxes'} drawn`,
      canvasLabel: 'Image to cover. Drag to draw a box.',
      applied: 'Covered version saved.',
    },
    story: {
      legend: 'Your story',
      label: 'What happened?',
      hint: "Tell it like you'd tell your homegirl. What happened, when, and what they said.",
      error: 'Write at least 20 characters, or record a voice note.',
      voiceTitle: 'Voice note',
      voiceHint: 'Optional. Up to 60 seconds.',
      record: 'Record voice note',
      stop: 'Stop',
      recording: (s: number) => `Recording, ${s} of 60 seconds`,
      recorded: (s: number) => `Voice note, ${s} seconds`,
      discard: 'Delete voice note',
      micDenied:
        'Microphone access was blocked. You can allow it in your browser settings, or type instead.',
      micUnsupported: 'Voice notes are not supported in this browser. Type instead.',
    },
    you: {
      legend: 'You and consent',
      signedInAs: (name: string) => `Sending as ${name}. You will see updates in your account.`,
      anonymousTitle: 'Sending without an account',
      anonymousBody:
        'You get a case code and a private claim code. Use both to check on your report. We cannot recover the claim code if you lose it.',
      signInInstead: 'Sign in with email or phone instead',
      age: 'I am 18 or older.',
      ageError: 'You need to be 18 or older to send a report.',
      truth: 'Everything I shared is true to the best of my knowledge.',
      truthError: 'Confirm that what you shared is true.',
      terms: 'I agree to the Terms and Privacy Policy.',
      termsError: 'You need to agree to the Terms and Privacy Policy.',
      termsLinks: 'Read the Terms and the Privacy Policy',
      contact: 'Vaden World can contact me about being featured.',
      contactHint: 'Optional. Anonymous reports cannot be contacted.',
      onCameraLegend: 'Being featured (optional)',
      onCamera: {
        yes: "I'm open to being on camera.",
        voice_only: 'Voice only.',
        anonymous_only: 'Anonymous only.',
        no: 'Not interested.',
      },
      required: 'Required',
    },
    review: {
      legend: 'Review and send',
      hint: 'Check everything. You can edit any step before you send.',
      nothing: 'Not given',
      submit: 'Send my report',
      sending: 'Sending',
      incomplete: 'Some steps need attention before you can send.',
      voiceNote: 'Voice note attached',
    },
    done: {
      title: 'Report received',
      caseCode: 'Case code',
      claimCode: 'Claim code',
      claimWarning: 'Save this claim code now. It is shown only once and we cannot recover it.',
      copy: 'Copy',
      copied: 'Copied',
      copyBoth: 'Copy both codes',
      next: 'What happens next',
      nextSteps: [
        'We check your files and remove hidden details.',
        'A person on our team reads your report, usually within a few days.',
        'If we need more, we ask (in your account, or on the status page with your codes).',
        'Nothing about the business goes public until two people on our team review it.',
      ],
      alsoReport: 'Also report it here',
      ftc: 'Federal Trade Commission: reportfraud.ftc.gov',
      ic3: 'FBI Internet Crime Complaint Center: ic3.gov',
      dispute: (rail: string) => `How to dispute a ${rail} payment`,
      disputeAny: 'How to dispute a payment',
      checkStatus: 'Check on your report',
      account: 'See it in your account',
    },
    status: {
      title: 'Check on your report',
      description: 'Use your case code and claim code to see where your report is.',
      lede: 'Enter the codes you got when you sent your report.',
      code: 'Case code',
      codeHint: 'Looks like RMMM-26-0412',
      claim: 'Claim code',
      claimHint: 'Looks like ABCD-EFGH-JKMN',
      submit: 'Check status',
      notFound: 'Those codes do not match a report. Check them and try again.',
      formatError: 'Check the format of both codes.',
      files: (n: number) => `${n} ${n === 1 ? 'file' : 'files'}`,
      processing: (n: number) => `${n} still being cleaned`,
      sent: 'Sent',
      states: {
        submitted: 'Received. We are checking your files.',
        triage: 'In the queue. A person on our team will read it soon.',
        needs_evidence: 'We need a bit more from you. Sign in or contact us with your case code.',
        ready_for_review: 'Under review by our team.',
        approved: 'Reviewed. Thank you.',
        rejected: 'Closed. We could not use this report.',
        withdrawn: 'Withdrawn.',
        draft: 'Not sent yet.',
      } as Record<string, string>,
    },
  },
  admin: {
    title: 'Admin',
    nav: {
      label: 'Admin',
      dashboard: 'Dashboard',
      reports: 'Reports',
      entities: 'Entities',
      flags: 'Flags',
      disputes: 'Disputes',
      bans: 'Bans',
      audit: 'Audit log',
      site: 'Back to site',
    },
    signedInAs: (name: string, role: string) => `${name}, ${role}`,
    you: 'You',
    roles: { moderator: 'Moderator', editor: 'Editor', admin: 'Admin' } as Record<string, string>,
    mfa: {
      title: 'Two-step verification',
      lede: 'Staff tools need a second step every time you sign in (SPEC 11). Use an authenticator app.',
      enroll: 'Set up an authenticator app',
      scan: 'Scan this code with your authenticator app, or enter the key by hand.',
      secret: 'Key',
      code: 'Six-digit code',
      verify: 'Verify',
      verifying: 'Checking',
      wrongCode: 'That code did not work. Codes change every 30 seconds; try the newest one.',
      unavailable: 'Sign-in is not configured on this site.',
      done: 'Verified. Opening the admin console.',
    },
    dashboard: {
      queue: 'Report queue',
      flagsOpen: (n: number) => `${n} open ${n === 1 ? 'flag' : 'flags'}`,
      flagsOverdue: (n: number) => `${n} past the 24-hour deadline`,
      disputesOpen: (n: number) => `${n} open ${n === 1 ? 'dispute' : 'disputes'}`,
      disputesOverdue: (n: number) => `${n} past the 7-day deadline`,
      entitiesAwaiting: (n: number) =>
        `${n} ${n === 1 ? 'entity' : 'entities'} waiting for a second approval`,
    },
    status: {
      draft: 'Draft',
      submitted: 'New',
      triage: 'Triage',
      needs_evidence: 'Needs evidence',
      ready_for_review: 'Ready for review',
      approved: 'Approved',
      rejected: 'Rejected',
      withdrawn: 'Withdrawn',
    } as Record<string, string>,
    table: {
      code: 'Case code',
      category: 'Category',
      submitted: 'Sent',
      files: 'Files',
      identifiers: 'Identifiers',
      signals: 'Signals',
      status: 'Status',
      name: 'Name',
      place: 'Place',
      reports: 'Reports',
      approvals: 'Approvals',
      created: 'Created',
      due: 'Deadline',
      target: 'About',
      reason: 'Reason',
      expires: 'Expires',
      never: 'Never',
      actions: 'Actions',
      when: 'When',
      who: 'Who',
      what: 'What',
    },
    empty: {
      reports: 'Nothing in this queue.',
      entities: 'No entities yet. Create one from a report.',
      flags: 'No open flags.',
      disputes: 'No disputes.',
      bans: 'No bans.',
      audit: 'No audit entries.',
    },
    signals: {
      deviceReports: (n: number) => `${n} reports from this device in 24 hours`,
      duplicateMedia: 'A file matches one sent with another report',
      rejectedFiles: (n: number) => `${n} ${n === 1 ? 'file' : 'files'} not accepted`,
      unscanned: 'Files not virus-scanned',
      none: 'No automated warnings',
    },
    report: {
      story: 'Story (reporter only, never public as written)',
      who: 'Identifiers they gave',
      money: 'Money',
      evidence: 'Evidence',
      checks: 'Automated checks',
      moderation: 'Moderation',
      entities: 'Linked entities',
      source: 'Source',
      noStory: 'No written story (voice note only).',
      original: 'Original',
      covered: 'Covered copy',
      openFile: (kind: string) => `Open ${kind}`,
      cover: 'Cover details',
      coverSaved: 'Covered copy saved. Only the covered copy can ever be published.',
      transcript: 'Transcript',
      ocr: 'Text found in the image',
      fileStatus: (s: string) => `File status: ${s}`,
      triage: 'Move to triage',
      ready: 'Ready for review',
      requestEvidence: 'Ask for more evidence',
      evidenceRequest: 'What do you need from the reporter?',
      evidenceRequestHint: "The reporter sees this message. Do not include other people's details.",
      publicExcerpt: 'Public excerpt',
      publicExcerptHint:
        "Quote the reporter's words. Remove names of private people, numbers, emails and payment details. Never add claims.",
      saveExcerpt: 'Save excerpt',
      approve: 'Approve report',
      reject: 'Reject report',
      rejectReason: 'Reason',
      rejectReasons: {
        not_enough_evidence: 'Not enough evidence',
        duplicate: 'Duplicate of another report',
        not_a_scam_report: 'Not about a business that took money',
        abusive: 'Abusive or harassing',
        spam: 'Spam or fake',
        withdrawn_by_reporter: 'Reporter asked to withdraw',
        other: 'Other',
      } as Record<string, string>,
      staffNote: 'Internal note',
      staffNoteHint: 'Staff only.',
      saveNote: 'Save note',
      saved: 'Saved',
      createEntity: 'Create entity from this report',
      entityName: 'Entity name',
      linkEntity: 'Link to an existing entity',
      searchEntities: 'Search entities by name',
      link: 'Link',
      unlink: 'Unlink',
      sourceKnown: (ip: boolean, device: boolean) =>
        `IP address ${ip ? 'recorded' : 'not recorded'}. Device ${device ? 'recorded' : 'not recorded'}. Staff never see the address itself.`,
      ban: "Ban this reporter's IP and device",
      banReason: 'Reason for the ban',
      banDuration: 'How long',
      banDurations: {
        '7': '7 days',
        '30': '30 days',
        '365': '1 year',
        forever: 'No end date',
      } as Record<string, string>,
      banConfirm: 'Ban now',
      banned: (ip: boolean, device: boolean) =>
        `Banned: ${[ip ? 'IP address' : null, device ? 'device' : null].filter(Boolean).join(' and ') || 'already banned'}. It takes effect on the next request.`,
      adminOnly: 'Only admins can ban.',
    },
    entity: {
      new: 'New entity',
      details: 'Details',
      identifiers: 'Identifiers',
      addIdentifier: 'Add identifier',
      identifierType: 'Type',
      identifierValue: 'Value',
      remove: 'Remove',
      reports: 'Reports linked',
      approvals: 'Approvals',
      approvalsHint:
        'Going public needs two different people: one moderator and one editor (admins count as either). Unpublishing clears approvals.',
      approve: 'Approve',
      withdraw: 'Withdraw my approval',
      publish: 'Make public',
      unpublish: 'Take down',
      public: 'Public',
      notPublic: 'Not public',
      awaiting: (n: number) => `${n} of 2 approvals`,
      legalHold: 'Legal hold',
      legalHoldOn: 'Legal hold is on. Edits, merges and deletes are frozen.',
      setHold: 'Turn on legal hold',
      liftHold: 'Lift legal hold',
      links: 'Linked pages',
      linksHint:
        'Links below 0.9 confidence need a person to confirm them before they show publicly.',
      confirm: 'Confirm',
      confirmed: 'Confirmed',
      addLink: 'Link another entity',
      merge: 'Merge another entity into this one',
      mergeHint:
        'Moves its identifiers, reports, links and disputes here, then deletes it. This cannot be undone.',
      mergeConfirm: (name: string) => `Merge ${name} into this entity`,
      linkReasons: {
        shared_cashtag: 'Shared payment tag',
        shared_phone: 'Shared phone',
        same_flyer_phash: 'Same flyer image',
        name_similarity: 'Similar name',
        staff_manual: 'Linked by staff',
      } as Record<string, string>,
      graphLabel: (n: number) =>
        `Link graph: this entity and ${n} linked ${n === 1 ? 'entity' : 'entities'}`,
      save: 'Save details',
      create: 'Create entity',
    },
    flags: {
      lede: 'Every flag gets a response within 24 hours (SPEC 10.7).',
      open: 'Open',
      resolved: 'Resolved',
      dueIn: (h: number, m: number) => `Due in ${h}h ${m}m`,
      overdue: (h: number, m: number) => `Overdue by ${h}h ${m}m`,
      resolve: 'Resolve',
      action: 'Action taken',
      actions: {
        removed: 'Removed the content',
        edited: 'Edited the content',
        no_action: 'No change needed',
        banned_user: 'Banned the account',
      } as Record<string, string>,
      note: 'Note',
      reasons: {
        inaccurate: 'Inaccurate',
        personal_info: 'Personal information',
        harassment: 'Harassment',
        hate: 'Hate',
        spam: 'Spam',
        legal: 'Legal',
        other: 'Other',
      } as Record<string, string>,
    },
    disputes: {
      lede: 'Businesses can answer with their own evidence. Review within 7 days and log the outcome (SPEC 10.6).',
      status: { open: 'Open', in_review: 'In review', resolved: 'Resolved' } as Record<
        string,
        string
      >,
      outcome: 'Outcome',
      outcomes: {
        content_updated: 'Content updated',
        annotated: 'Business response added',
        content_removed: 'Content removed',
        no_change: 'No change',
      } as Record<string, string>,
      startReview: 'Start review',
      resolve: 'Resolve',
      from: 'From',
      entity: 'Entity',
    },
    bans: {
      lede: 'Bans apply on the next request, everywhere: website, app and direct API calls.',
      ip: 'IP addresses and ranges',
      device: 'Devices',
      accounts: 'Accounts',
      add: 'Add IP bans',
      addresses: 'Addresses or ranges, one per line',
      addressesHint: 'Examples: 203.0.113.7 or 203.0.113.0/24. Up to 100 at once.',
      reason: 'Reason',
      days: 'Days until it ends (empty for no end date)',
      submit: 'Ban',
      lift: 'Lift',
      search: 'Search',
      invalid: (v: string) => `Not an IP address or range: ${v}`,
      added: (n: number) => `${n} ${n === 1 ? 'ban' : 'bans'} added.`,
      banAccount: 'Ban an account',
      accountId: 'Account id',
      unbanAccount: 'Lift account ban',
    },
    audit: {
      lede: 'Every staff action, newest first. Entries cannot be edited or deleted.',
      filter: 'Filter by table',
      all: 'Everything',
    },
    errors: {
      forbidden: 'You do not have permission for that.',
      twoPerson:
        'Not yet: going public needs approval from a moderator and an editor, two different people.',
      legalHold: 'This is under legal hold.',
      generic: 'That did not work. Try again.',
    },
  },
  time: {
    today: 'today',
    yesterday: 'yesterday',
    daysAgo: (n: number) => `${n} days ago`,
    weeksAgo: (n: number) => `${n} ${n === 1 ? 'week' : 'weeks'} ago`,
    monthsAgo: (n: number) => `${n} ${n === 1 ? 'month' : 'months'} ago`,
    yearsAgo: (n: number) => `${n} ${n === 1 ? 'year' : 'years'} ago`,
  },
} as const;

export type Strings = typeof en;
