#!/usr/bin/env node
/**
 * Syncs brand/ into the apps.
 *  - copies every SVG to apps/web/public/brand (served as static files)
 *  - generates packages/ui/src/icons/generated.ts (icon geometry + raw brand SVGs for RN)
 * `--check` fails if anything is out of date (used in CI).
 */
import fs from 'node:fs';
import path from 'node:path';

const root = path.resolve(import.meta.dirname, '..');
const brand = path.join(root, 'brand');
const webOut = path.join(root, 'apps/web/public/brand');
const genOut = path.join(root, 'packages/ui/src/icons/generated.ts');
const check = process.argv.includes('--check');
let stale = [];

function write(file, content) {
  const prev = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : null;
  if (prev === content) return;
  if (check) return stale.push(path.relative(root, file));
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, content);
}

const svgFiles = (dir) =>
  fs
    .readdirSync(dir)
    .filter((f) => f.endsWith('.svg'))
    .sort();

// 1. copy to web/public
for (const f of svgFiles(brand))
  write(path.join(webOut, f), fs.readFileSync(path.join(brand, f), 'utf8'));
for (const f of svgFiles(path.join(brand, 'icons')))
  write(path.join(webOut, 'icons', f), fs.readFileSync(path.join(brand, 'icons', f), 'utf8'));

// 2. icon geometry
const ELEMENT = /<(path|circle|rect|line|polyline|polygon|ellipse)\b([^>]*?)\/?>/g;
const ATTR = /([a-zA-Z-]+)="([^"]*)"/g;
const camel = (s) => s.replace(/-([a-z])/g, (_, c) => c.toUpperCase());
const icons = {};
for (const f of svgFiles(path.join(brand, 'icons'))) {
  const src = fs.readFileSync(path.join(brand, 'icons', f), 'utf8');
  const name = f.replace(/\.svg$/, '');
  icons[name] = [...src.matchAll(ELEMENT)].map(([, tag, attrs]) => ({
    tag,
    attrs: Object.fromEntries([...attrs.matchAll(ATTR)].map(([, k, v]) => [camel(k), v])),
  }));
  if (!icons[name].length) throw new Error(`No shapes found in brand/icons/${f}`);
}

const raw = {};
for (const f of svgFiles(brand)) {
  raw[f.replace(/\.svg$/, '')] = fs
    .readFileSync(path.join(brand, f), 'utf8')
    .replace(/<\?xml[^>]*>\s*/, '')
    .replace(/<!--[\s\S]*?-->\s*/g, '')
    .trim();
}

const ts = `// GENERATED by scripts/sync-brand.mjs from brand/. Do not edit by hand.
/* eslint-disable */

export interface IconShape {
  tag: 'path' | 'circle' | 'rect' | 'line' | 'polyline' | 'polygon' | 'ellipse';
  attrs: Record<string, string>;
}

export const iconShapes = ${JSON.stringify(icons, null, 2)} as const satisfies Record<string, readonly IconShape[]>;

export type IconName = keyof typeof iconShapes;

/** Raw brand SVG markup (for react-native-svg SvgXml). Web uses /brand/*.svg instead. */
export const brandSvg = ${JSON.stringify(raw, null, 2)} as const;

export type BrandAsset = keyof typeof brandSvg;
`;
write(genOut, ts);

if (check && stale.length) {
  console.error(`Brand assets out of date. Run \`pnpm brand:sync\`.\n  ${stale.join('\n  ')}`);
  process.exit(1);
}
console.log(check ? 'brand: up to date' : 'brand: synced');
